## NumPy

NumPy es una librería fundamental para la computación científica en Python. Su función principal es la creación y manipulación de arrays multidimensionales (ndarray), los cuales son más rápidos y eficientes en memoria que las listas de Python. Además, ofrece una vasta colección de funciones matemáticas y estadísticas de alto nivel.

- Establer los paquetes de manera ordenada

In [1]:
import numpy as np

- Ejemplo de array unidimensional (Vector)

In [8]:
array_1d = np.array([1,2,3])
print(array_1d)
type(array_1d)

[1 2 3]


numpy.ndarray

- Ejemplo de Array Bidimensional (Matriz)

In [7]:
array_2d = np.array([[1,2,3], [1,2,3]])
print(array_2d)
type(array_2d)

[[1 2 3]
 [1 2 3]]


numpy.ndarray

- Ejemplo de Array Multidimensional (Tensor)

In [9]:
array_3d = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])
print(array_3d)
type(array_3d)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


numpy.ndarray

Se utiliza NumPy en vez de Lista de Python, esto ocupa menos memoria y es más rápido.